version: 2

updates:

  - package-ecosystem: pip
    # setup.py for provider
    directory: '/provider'
    schedule:
      interval: daily
    assignees:
      - sergeyklay

  - package-ecosystem: pip
    # setup.py for consumer
    directory: '/consumer'
    schedule:
      interval: daily
    assignees:
      - sergeyklay

  - package-ecosystem: github-actions
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: '/'
    schedule:
      interval: daily
    assignees:
      - sergeyklay

  - package-ecosystem: npm
    # package.json stored in repository root.
    directory: /
    schedule:
      interval: daily
    assignees:
      - sergeyklay
