# This file is part of the Provider API Example.
#
# Copyright (C) 2023 Serghei Iakovlev <egrep@protonmail.ch>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

'open api':
  - '.redocly.yaml'
  - 'openapi/*.yaml'

python:
    - '**/*.py'
    - 'setup.cfg'
    - 'provider/**/*'
    - 'requirements/*.in'
    - 'requirements/*.txt'

javascript:
  - 'package.json'
  - 'package-lock.json'

dependencies:
  - 'package.json'
  - 'package-lock.json'
  - 'requirements/*.in'
  - 'requirements/*.txt'

github_actions:
  - '.github/workflows/*.yaml'

documentation:
  - '*.rst'
