# This file is part of the Contract Testing Example.
#
# Copyright (C) 2023 Serghei Iakovlev <egrep@protonmail.ch>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

'open api':
  - 'openapi/*.yaml'

provider:
  - any: ['provider/**/*']

consumer:
  - any: ['consumer/**/*']

github_actions:
  - any: ['.github/**/*']

documentation:
  - '*.rst'
