# This file is part of the Contract Testing Example.
#
# Copyright (C) 2023 Serghei Iakovlev <egrep@protonmail.ch>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

extends: [[spectral:oas, all]]

rules:
  path-keys-no-trailing-slash: error
  oas3-valid-media-example: warn
