---
openapi: 3.0.3

info:
  version: '1.0'
  title: Products API Definition
  description: Example API to test Specmatic features.
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  contact:
    name: Bug Tracker
    url: https://github.com/sergeyklay/specmatic-testing-example/issues
    email: egrep@protonmail.ch

servers:
  - description: Localhost
    url: http://127.0.0.1:5000

tags:
  - name: products
    description: Products related API.

components:
  schemas:
    Product:
      title: Product
      type: object
      properties:
        id:
          type: integer
          format: int32
          minimum: 1
          example: 42
        self_url:
          type: string
          example: https://example.com/v1/products/1
        title:
          type: string
          example: iPhone 9
          minLength: 1
          maxLength: 64
        description:
          type: string
          example: An Apple mobile which is nothing like apple
          minLength: 0
          maxLength: 512
        price:
          type: number
          minimum: 0
          example: 549
        discount:
          type: number
          minimum: 0.0
          example: 12.96
        rating:
          type: number
          minimum: 0.0
          maximum: 5.0
          example: 4.69
        stock:
          type: integer
          format: int32
          minimum: 0
          example: 856
        brand:
          type: string
          example: Apple, Inc.
          minLength: 1
          maxLength: 64
        category:
          $ref: '#/components/schemas/ProductCategory'
      required:
        - id
        - self_url
        - title
        - description
        - price
        - discount
        - rating
        - stock
        - brand
        - category
    ProductCategory:
      title: Product Category
      type: string
      enum:
        - smartphones
        - laptops
      example: smartphones
    Pages:
      title: Pages
      type: object
      properties:
        first_url:
          type: string
          example: https://example.com/v1/products?page=1&per_page=10
        last_url:
          type: string
          example: https://example.com/v1/products?page=30&per_page=10
        next_url:
          type: string
          example: https://example.com/v1/products?page=3&per_page=10
          nullable: true
        prev_url:
          type: string
          example: https://example.com/v1/products?page=1&per_page=10
          nullable: true
        page:
          type: integer
          format: int32
          minimum: 1
          example: 7
        pages:
          type: integer
          format: int32
          minimum: 0
          example: 30
        per_page:
          type: integer
          format: int32
          minimum: 1
          example: 30
        total:
          type: integer
          format: int32
          minimum: 0
          example: 300
    NotFoundResponse:
      title: Not Found Response
      type: object
      required:
        - status
        - title
        - description
      properties:
        status:
          type: integer
          format: int32
          example: 404
        title:
          type: string
          example: Not Found
        description:
          type: string
          example: Specified product not found
  parameters:
    ProductIdParameter:
      in: path
      name: id
      description: Product ID param
      schema:
        type: integer
        format: int32
        minimum: 1
      required: true
      examples:
        success:
          summary: An ID of an existing product
          value: 42
        not-found:
          summary: An ID of an not existing product
          value: 10000000

paths:
  /v1/products:
    get:
      summary: Get list of products,
      description: Returns a list of all products.
      operationId: products.index
      tags: [products]
      parameters:
        - in: query
          name: expanded
          description: Return collection of links to products (0) or expanded response (1).
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 1
          examples:
            expanded:
              value: 1
              summary: A response with full products detail
            collapsed:
              value: 0
              summary: A response with products links only
        - in: query
          name: category
          description: Filter by product category.
          required: false
          schema:
            type: string
          examples:
            laptops:
              value: laptops
              summary: Products from the "laptops" category
            smartphones:
              value: smartphones
              summary: Products from the "smartphones" category
        - in: query
          name: q
          description: Search term.
          required: false
          schema:
            type: string
          examples:
            term:
              value: Samsung
              summary: A sample search keyword.
      responses:
        '200':
          description: List of products
          headers:
            ETag:
              description: The ETag HTTP response header is an identifier for a specific version of a resource.
              schema:
                type: string
                minLength: 34
                maxLength: 34
              example: '"c1983e057880c5d40817708584401e4d"'
          content:
            application/json:
              schema:
                type: object
                required:
                  - pages
                  - products
                properties:
                  pages:
                    $ref: '#/components/schemas/Pages'
                  products:
                    oneOf:
                      - type: array
                        items:
                          $ref: '#/components/schemas/Product'
                      - type: array
                        items:
                          type: string
              examples:
                expanded:
                  value:
                    pages:
                      first_url: https://example.com/v1/products?page=1&per_page=10
                      last_url: https://example.com/v1/products?page=30&per_page=10
                      next_url: https://example.com/v1/products?page=3&per_page=10
                      prev_url: https://example.com/v1/products?page=1&per_page=10
                      page: 2
                      pages: 30
                      per_page: 10
                      total: 300
                    products:
                      - id: 1
                        self_url: https://example.com/v1/products/1
                        title: iPhone 9
                        description: An Apple mobile which is nothing like apple
                        price: 549
                        discount: 12.96
                        rating: 4.69
                        stock: 94
                        brand: Apple
                        category: smartphones
                      - id: 6
                        self_url: https://example.com/v1/products/6
                        title: Samsung Galaxy Book
                        description: Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched
                        price: 1499
                        discount: 4.15
                        rating: 4.25
                        stock: 50
                        brand: Samsung
                        category: laptops
                  summary: A response with full products detail
                collapsed:
                  value:
                    pages:
                      first_url: https://example.com/v1/products?page=1&per_page=10
                      last_url: https://example.com/v1/products?page=30&per_page=10
                      next_url: https://example.com/v1/products?page=3&per_page=10
                      prev_url: https://example.com/v1/products?page=1&per_page=10
                      page: 2
                      pages: 30
                      per_page: 10
                      total: 300
                    products:
                      - https://example.com/v1/products/1
                      - https://example.com/v1/products/2
                      - https://example.com/v1/products/3
                      - https://example.com/v1/products/4
                      - https://example.com/v1/products/5
                      - https://example.com/v1/products/6
                      - https://example.com/v1/products/8
                      - https://example.com/v1/products/9
                      - https://example.com/v1/products/10
                  summary: A response with products links only
  '/v1/products/{id}':
    get:
      summary: Get single product.
      description: Returns a single product.
      operationId: products.get
      tags: [products]
      parameters:
        - $ref: '#/components/parameters/ProductIdParameter'
      responses:
        '200':
          description: A product
          headers:
            ETag:
              description: The ETag HTTP response header is an identifier for a specific version of a resource.
              schema:
                type: string
                minLength: 34
                maxLength: 34
              example: '"c1983e057880c5d40817708584401e4d"'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              examples:
                iPhone:
                  value:
                    id: 1
                    self_url: https://example.com/v1/products/1
                    title: iPhone 9
                    description: An Apple mobile which is nothing like apple
                    price: 549
                    discount: 12.96
                    rating: 4.69
                    stock: 94
                    brand: Apple
                    category: smartphones
                Samsung:
                  value:
                    id: 6
                    self_url: https://example.com/v1/products/6
                    title: Samsung Galaxy Book
                    description: Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched
                    price: 1499
                    discount: 4.15
                    rating: 4.25
                    stock: 50
                    brand: Samsung
                    category: laptops
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
    delete:
      summary: Delete product.
      description: Deletes a specific product and returns status code 204 if successful, otherwise - 404.
      operationId: products.delete
      tags: [ products ]
      parameters:
        - $ref: '#/components/parameters/ProductIdParameter'
      responses:
        '204':
          description: Successful operation
        '404':
          description: Product not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
