name: Check Contracts

on: [push]

jobs:
  hello_world_job:

    runs-on: ${{ matrix.os }}
    name: Test Contracts

    strategy:
      # When set to true, GitHub cancels
      # all in-progress jobs if any matrix job fails.
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API server
        if: matrix.os != 'windows-latest'
        run: flask run --port 5000 &
        env:
          FLASK_APP: server.py
          FLASK_ENV: development

      - name: Run API server
        if: matrix.os == 'windows-latest'
        run: Start-Process -NoNewWindow flask run -ArgumentList '--port 5000'
        env:
          FLASK_APP: server.py
          FLASK_ENV: development


      - name: Setup specmatic
        uses: airslate-oss/setup-specmatic@v1
        with:
          specmatic-version: stable

      - name: Test specification
        run: specmatic test --testBaseURL=http://127.0.0.1:5000
