name: Check Contracts

on: [push]

jobs:
  check-contracts:

    runs-on: ${{ matrix.os }}
    name: Test Contracts

    strategy:
      # When set to true, GitHub cancels
      # all in-progress jobs if any matrix job fails.
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup cache on Linux
        uses: actions/cache@v3
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup cache on macOS
        uses: actions/cache@v3
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup cache on Windows
        uses: actions/cache@v3
        if: matrix.os == 'windows-latest'
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API server
        run: flask --app runner:app run &
        shell: bash

      - name: Setup specmatic
        uses: airslate-oss/setup-specmatic@v1
        with:
          specmatic-version: stable

      - name: Test specification
        run: specmatic test --testBaseURL=http://127.0.0.1:5000

      - name: Get changed yaml files
        id: changed-oas-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            contracts/**/*.yaml

      - name: Show changed files
        run: |
          echo "Changed files are: ${{ steps.changed-oas-files.outputs.all_changed_files }}"
        shell: bash
    
      - name: Run backward compatibility check on changed files
        if: steps.changed-oas-files.outputs.any_changed == 'true'
        run: |
          echo "${{ steps.changed-oas-files.outputs.all_changed_files }}" | tr -s ' ' '\n' | xargs -I % specmatic compatible git commits % main HEAD
        shell: bash
