name: Lint OpenAPI

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

jobs:
  lint-openapi:
    name: Lint OpenAPI spec
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          # Number of commits to fetch. 0 indicates all history for all branches and tags.
          fetch-depth: 0

      - name: Get changed yaml files
        id: changed-oas-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            contracts/*.yaml

      - name: Show changed files
        run: |
          echo "Changed files are: ${{ steps.changed-oas-files.outputs.all_changed_files }}"

      - name: Set up Go
        if: steps.changed-oas-files.outputs.any_changed == 'true'
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install Vacuum
        if: steps.changed-oas-files.outputs.any_changed == 'true'
        run: go install github.com/daveshanley/vacuum@v0.0.50
  
      - name: Run vacuum linter
        if: steps.changed-oas-files.outputs.any_changed == 'true'
        run: vacuum lint --no-style -d -e contracts/documentation.yaml

      - name: Setup Node.js 16.x
        if: steps.changed-oas-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Setup cache
        uses: actions/cache@v3
        if: steps.changed-oas-files.outputs.any_changed == 'true'
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.changed-oas-files.outputs.any_changed == 'true'
        run: npm ci --ignore-scripts

      - name: Run openapi-enforcer linter
        if: steps.changed-oas-files.outputs.any_changed == 'true'
        run: npm run lint-enforcer

      - name: Run redocly linter
        if: steps.changed-oas-files.outputs.any_changed == 'true'
        run: npm run lint-redocly

      - name: Run spectral linter
        if: steps.changed-oas-files.outputs.any_changed == 'true'
        run: npm run lint-spectral
