name: Lint OpenAPI

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

jobs:
  lint-openapi:
    name: Lint OpenAPI spec
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Install Vacuum
        run: go install github.com/daveshanley/vacuum@v0.0.50
  
      - name: Run vacuum linter
        run: vacuum lint --no-style -d -e contracts/documentation.yaml

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run redocly and openapi-enforcer linters
        run: npm run lint
