name: Lint OpenAPI

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'

jobs:
  lint-openapi:
    name: Lint OpenAPI spec
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Install linters
        run: npm run lint
