name: Test

on: [push]

jobs:
  hello_world_job:

    runs-on: ubuntu-latest
    name: A job to test custom actions

    steps:
      - name: Checkout
        uses: actions/checkout@v3
 
      - name: Hello world action step
        id: hello
        uses: sergeyklay/hello-world-javascript-action@v1.5
        with:
          who-to-greet: 'Mona the Octocat'

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setup specmatic
        id: specmatic
        uses: airslate-oss/setup-specmatic@v0.0.21
        with:
          specmatic-version: 0.59.0

      - name: Test
        run: |
          ls -al /opt/hostedtoolcache/specmatic || true
          ls -al /opt/hostedtoolcache/specmatic/0.59.0 || true
          ls -al /opt/hostedtoolcache/specmatic/0.59.0/x64 || true

          echo $PATH

          if [ -f /opt/hostedtoolcache/specmatic/0.59.0/x64/specmatic.jar ]; then
            java -jar /opt/hostedtoolcache/specmatic/0.59.0/x64/specmatic.jar --version
          fi

          type -a specmatic
          command -v specmatic

          specmatic --version
