name: Test

on: [push]

jobs:
  hello_world_job:

    runs-on: ${{ matrix.os }}
    name: Rest action

    strategy:
      # When set to true, GitHub cancels
      # all in-progress jobs if any matrix job fails.
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check cache before install
        if: matrix.os != 'windows-latest'
        run: |
          if [ -d /opt/hostedtoolcache ]; then
            ls -l /opt/hostedtoolcache
          fi

      - name: Check cache before install
        if: matrix.os == 'windows-latest'
        run: |
          if (Test-Path -Path "C:\hostedtoolcache\windows") {
            Get-ChildItem "C:\hostedtoolcache\windows"
          }

      - name: Setup specmatic
        uses: airslate-oss/setup-specmatic@dc49c26cebcd0698c8b53e19cfad50363fc05392
        with:
          specmatic-version: stable

      - name: Check cache after install
        if: matrix.os != 'windows-latest'
        run: |
          if [ -d /opt/hostedtoolcache ]; then
            ls -l /opt/hostedtoolcache
          fi

      - name: Print wrapper contents
        if: matrix.os != 'windows-latest'
        run: |
          if [ -f /opt/hostedtoolcache/specmatic/0.59.0/x64/specmatic ]; then
            cat /opt/hostedtoolcache/specmatic/0.59.0/x64/specmatic
          fi

      - name: Check cache after install
        if: matrix.os == 'windows-latest'
        run: |
          if (Test-Path -Path "C:\hostedtoolcache\windows") {
            Get-ChildItem "C:\hostedtoolcache\windows"
          }

      - name: Print wrapper contents
        if: matrix.os == 'windows-latest'
        run: |
          if (Test-Path -Path "C:\hostedtoolcache\windows\specmatic\0.59.0\x64\specmatic") {
            Get-Content "C:\hostedtoolcache\windows\specmatic\0.59.0\x64\specmatic"
            Rename-Item -Path "C:\hostedtoolcache\windows\specmatic\0.59.0\x64\specmatic" -NewName "specmatic.bat"
          }

      - name: Find Java
        if: matrix.os != 'windows-latest'
        run: type -a java

      - name: Find specmatic
        if: matrix.os != 'windows-latest'
        run: type -a specmatic

      - name: Check specmatic version
        run: specmatic --version

      - name: Check specmatic version using jar file
        if: matrix.os == 'windows-latest'
        run: |
          if (Test-Path -Path "C:\hostedtoolcache\windows\specmatic\0.59.0\x64\specmatic.jar") {
            java -jar "C:\hostedtoolcache\windows\specmatic\0.59.0\x64\specmatic.jar" --version
          }

      - name: Check specmatic version using test file
        if: matrix.os == 'windows-latest'
        run: |
          if (Test-Path -Path "C:\hostedtoolcache\windows\specmatic\0.59.0\x64\specmatic.jar") {
            specmatic-test.bat --version
          }
