name: Test

on: [push]

jobs:
  hello_world_job:

    runs-on: ubuntu-latest
    name: A job to test custom actions

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup specmatic
        id: specmatic
        uses: airslate-oss/setup-specmatic@v0
        with:
          specmatic-version: 0.59.0

      - name: Check cache
        run: |
          if [ -f /opt/hostedtoolcache/specmatic/0.59.0/x64/specmatic ]; then
            cat /opt/hostedtoolcache/specmatic/0.59.0/x64/specmatic
          fi

      - name: Find Java
        run: type -a java

      - name: Find specmatic
        run: type -a specmatic

      - name: Check specmatic version
        run: specmatic --version
